from __future__ import annotations


OVERALL_ANALYSIS_TARGET_STATIONS = [
    "Zürich HB",
    "Zürich Oerlikon",
    "Winterthur",
    "Zürich Altstetten",
    "Bern",
    "Olten",
    "Zürich Flughafen",
    "Zug",
    "Genève",
    "Baden",
    "Aarau",
    "Thalwil",
    "Lausanne",
    "Dietikon",
    "Thun",
    "Spiez",
    "Weinfelden",
    "Pfäffikon SZ",
    "Frauenfeld",
    "Brugg AG",
    "Wettingen",
    "Nyon",
    "Morges",
    "St. Gallen",
    "Basel SBB",
    "Romanshorn",
    "Luzern",
    "Arth-Goldau",
    "Wädenswil",
    "Sargans",
    "Wil SG",
    "Schaffhausen",
    "Neuhausen",
    "Lenzburg",
    "Bülach",
    "Baar",
    "Visp",
    "Bellinzona",
    "Amriswil",
    "Rapperswil SG",
    "Biel/Bienne",
    "Solothurn",
    "Neuchâtel",
    "Turgi",
    "Aigle",
    "Montreux",
    "Vevey",
    "Lugano",
    "Jegenstorf",
    "Bätterkinden",
    "Lohn-Lüterkofen",
    "Landquart",
    "Biberist RBS",
    "Gossau SG",
    "Andelfingen",
    "Fribourg/Freiburg",
    "Liestal",
    "Brig",
    "Rorschach",
    "Romont FR",
    "Ziegelbrücke",
    "Interlaken West",
    "Yverdon-les-Bains",
    "Langenthal",
    "Burgdorf",
    "St. Margrethen SG",
    "Buchs SG",
    "La Chaux-de-Fonds",
    "Kreuzlingen",
    "St-Maurice",
    "Martigny",
    "Bex",
    "Sion",
    "Sierre/Siders",
    "Faido",
    "Airolo",
    "Interlaken Ost",
    "Göschenen",
    "Delémont",
    "Moutier",
    "Biasca",
    "Heerbrugg",
    "Lyss",
    "Altstätten SG",
    "Fraubrunnen",
    "Laufen",
    "Erstfeld",
    "Konolfingen",
    "Chur",
    "Grenchen Nord",
    "Flüelen",
    "Bad Ragaz",
    "Brunnen",
    "Rheinfelden",
    "Herzogenbuchsee",
    "Sissach",
    "Frick",
    "Ins",
    "Kerzers",
    "Oensingen",
    "Chiasso",
    "Bulle",
    "Sursee",
    "Zofingen",
    "Hohtenn",
    "Goppenstein",
    "Ausserberg",
    "Eggerberg",
    "Kandersteg",
    "Frutigen",
    "Herisau",
    "Konstanz",
    "Brienz",
    "Leuk",
    "Meiringen",
    "Palézieux",
    "Brünig-Hasliberg",
    "St-Imier",
    "Lungern",
    "Courtelary",
    "Langnau i.E.",
    "Sonceboz-Sombeval",
    "Giswil",
    "Sarnen",
    "Wattwil",
    "Wolhusen",
    "Grenchen Süd",
    "Küssnacht am Rigi",
    "Uznach",
    "Biberbrugg",
    "Le Locle",
]
